### ISSUE TITLE
Build failure on macOS Big Sur

### ISSUE THREAD

**Issue by brightly-salty** [Smithay/calloop#31]
When I try to build calloop (as a dependency of client-toolkit) on macOS Big Sur 10.1, I get the following error messages:
```
MacBook :: Desktop/client-toolkit » cargo check
    Checking calloop v0.6.5
error[E0432]: unresolved import `nix::unistd::pipe2`
  --> /Users/cadenhaustein/.cargo/registry/src/github.com-1ecc6299db9ec823/calloop-0.6.5/src/sources/ping.rs:18:21
   |
18 |     unistd::{close, pipe2, read, write},
   |                     ^^^^^
   |                     |
   |                     no `pipe2` in `unistd`
   |                     help: a similar name exists in the module: `pipe`

error[E0433]: failed to resolve: use of undeclared type `Poller`
   --> /Users/cadenhaustein/.cargo/registry/src/github.com-1ecc6299db9ec823/calloop-0.6.5/src/sys/mod.rs:172:21
    |
172 |             poller: Poller::new()?,
    |                     ^^^^^^ use of undeclared type `Poller`

error[E0412]: cannot find type `Poller` in this scope
   --> /Users/cadenhaustein/.cargo/registry/src/github.com-1ecc6299db9ec823/calloop-0.6.5/src/sys/mod.rs:166:13
    |
166 |     poller: Poller,
    |             ^^^^^^ not found in this scope

error: aborting due to 3 previous errors

Some errors have detailed explanations: E0412, E0432, E0433.
For more information about an error, try `rustc --explain E0412`.
error: could not compile `calloop`
```

**Comment by vberger** [comment]
Indeed, macOS support is not yet implemented in calloop.

We do have a *BSD kqueue implementation that might be compatible with macOS or not, but we need someone who knows about this stuff to ensure this is the case.

**Comment by curtisforrester** [comment]
I can confirm that this is also still an issue in Big Sur 11.5.2 - this, due to this [this change](https://github.com/nix-rust/nix/pull/1255) in the "nix" crate. They've removed support for that function on Mac in general it seems. 

Disappointing since I was pondering switching to calloop for handling an event loop in our server. Might dig into it later.

**Comment by curtisforrester** [comment]
I can confirm that this is also still an issue in Big Sur 11.5.2 - this, due to this [this change](https://github.com/nix-rust/nix/pull/1255) in the "nix" crate. They've removed support for that function on Mac in general it seems. 

Disappointing since I was pondering switching to calloop for handling an event loop in our server. Might dig into it later.

**Comment by curtisforrester** [comment]
I would like to gently suggest that a note be added that this library does not support Mac to save some time for those of us who develop on Mac (even though, in my case, the final target of the software is generally Linux).

**Comment by vberger** [comment]
Well, it is already in the readme:

> **Platforms support**
>
> Currently, only Linux and the *BSD are supported.

Are you suggesting something more?

**Comment by vberger** [comment]
Since 0.10 calloop is now working and tested on macOS.
